package com.liyuanjinglyj.jsweather.common;

import java.util.HashMap;
import java.util.Map;

public class WeatherImageMap {
    public Map<String,String> map=new HashMap<>();

    public Map<String, String> getMap() {
        map.put("雷阵雨","common/shower.png");
        map.put("小雨","common/rain.png");
        map.put("阴","common/overcast.png");
        map.put("多云","common/cloudy.png");

        map.put("晴","common/fine.png");
        map.put("雨夹雪","common/snow_2.png");
        map.put("雨","common/rain.png");
        map.put("中雨","common/rain_2.png");
        map.put("阵雨","common/shower.png");
        map.put("小雪","common/snow.png");
        map.put("雪","common/snow.png");
        map.put("中雪","common/snow_2.png");
        map.put("大雪","common/snow_2.png");
        map.put("大雨","common/shower.png");
        map.put("雾","common/smog.png");
        map.put("暴雨","common/shower.png");
        map.put("阵雪","common/snow_2.png");
        map.put("暴雪","common/snow_2.png");
        map.put("扬沙","common/yangsha.png");
        map.put("大暴雨","common/shower.png");
        map.put("霾","common/smog.png");
        map.put("浮尘","common/yangsha.png");

        map.put("晴转多云","common/fine.png");
        map.put("小雪转晴","common/fine.png");
        map.put("多云转晴","common/fine.png");
        map.put("多云转阴","common/fine.png");
        map.put("晴转阴","common/fine.png");
        map.put("阴转多云","common/cloudy.png");
        map.put("多云转小雪","common/snow.png");
        map.put("阵雪转晴","common/fine.png");
        map.put("晴转阵雪","common/snow_2.png");
        map.put("小雪转多云","common/cloudy.png");
        map.put("小雨转多云","common/cloudy.png");
        map.put("晴转小雪","common/snow.png");
        map.put("多云转雨夹雪","common/snow_2.png");
        map.put("多云转阵雪","common/snow_2.png");
        map.put("阵雨转多云","common/cloudy.png");
        map.put("多云转小雨","common/rain.png");
        map.put("多云转阵雨","common/shower.png");
        map.put("阵雪转小雪","common/snow.png");
        map.put("阴转小雪","common/snow.png");
        map.put("小雪转阴","common/overcast.png");
        map.put("阵雪转多云","common/cloudy.png");
        map.put("阴转晴","common/fine.png");
        map.put("阴转阵雪","common/snow_2.png");
        map.put("阵雪转阴","common/snow_2.png");
        map.put("扬沙转多云","common/yangsha.png");
        map.put("扬沙转晴","common/yangsha.png");
        map.put("浮尘转晴","common/yangsha.png");
        map.put("晴转雨夹雪","common/snow_2.png");
        map.put("多云转中雪","common/snow_2.png");
        map.put("晴转中雪","common/snow_2.png");
        map.put("阴转小雨","common/rain.png");
        map.put("小雨转中雨","common/rain_2.png");
        map.put("小雨转阴","common/overcast.png");
        map.put("中雨转多云","common/cloudy.png");
        map.put("中雨转小雨","common/rain.png");
        map.put("阴转中雨","common/rain_2.png");
        map.put("多云转中雨","common/rain_2.png");
        map.put("小雨转大雨","common/rain_2.png");
        map.put("阵雨转中雨","common/rain_2.png");
        map.put("阵雨转大雨","common/rain_2.png");
        map.put("阴转大雨","common/rain_2.png");
        map.put("雾转多云","common/yangsha.png");
        map.put("阵雨转小雨","common/rain.png");
        map.put("中雨转阴","common/overcast.png");
        map.put("晴转小雨","common/rain.png");
        map.put("多云转大雨","common/rain_2.png");
        map.put("小雨转暴雨","common/rain_2.png");
        map.put("阵雨转晴","common/fine.png");
        map.put("小雨转晴","common/fine.png");
        map.put("阵雨转中到大雨","common/rain_2.png");
        map.put("小雨转阵雨","common/rain_2.png");
        map.put("阵雨转阴","common/overcast.png");
        map.put("雨夹雪转晴","common/fine.png");
        map.put("雨夹雪转多云","common/cloudy.png");
        map.put("小雨转小雪","common/snow.png");
        map.put("小雪转雨夹雪","common/snow_2.png");
        map.put("阴转阵雨","common/rain_2.png");
        map.put("小雨转小到中雨","common/rain_2.png");
        map.put("小到中雨转小雨","common/rain.png");
        map.put("小到中雨转阴","common/overcast.png");
        map.put("晴转阵雨","common/rain_2.png");
        map.put("中雨转阵雨","common/rain_2.png");
        map.put("阵雨转雷阵雨","common/rain_2.png");
        map.put("多云转大雪","common/snow_2.png");
        map.put("阴转中雪","common/snow_2.png");
        map.put("阴转大雪","common/snow_2.png");
        map.put("雨夹雪转阴","common/overcast.png");
        map.put("雨夹雪转小雪","common/snow.png");
        map.put("小雨转大雪","common/snow_2.png");
        map.put("雨夹雪转大雪","common/snow_2.png");
        map.put("雨夹雪转中雪","common/snow_2.png");
        map.put("中雨转小雪","common/snow.png");
        map.put("中雨转中雪","common/snow_2.png");
        map.put("晴转大雪","common/snow_2.png");
        map.put("小雨转雨夹雪","common/snow_2.png");
        map.put("阴转雨夹雪","common/snow_2.png");
        map.put("多云转雾","common/smog.png");
        map.put("小雪转阵雪","common/snow_2.png");
        map.put("小雪转中雪","common/snow_2.png");
        map.put("多云转小到中雪","common/snow_2.png");
        map.put("中雪转多云","common/cloudy.png");
        map.put("中雪转小雪","common/snow.png");
        map.put("大雪转小雪","common/snow.png");
        map.put("中雨转大雨","common/rain_2.png");
        map.put("阵雨转雨夹雪","common/snow_2.png");
        map.put("多云转小到中雨","common/rain_2.png");
        map.put("小到中雨","common/rain_2.png");
        map.put("小到中雨转阵雨","common/rain_2.png");
        map.put("小雨转阵雪","common/snow_2.png");
        map.put("雷阵雨转多云","common/cloudy.png");
        map.put("雷阵雨转阵雨","common/rain_2.png");
        map.put("多云转扬沙","common/yangsha.png");
        map.put("晴转扬沙","common/yangsha.png");
        map.put("扬沙转阴","common/yangsha.png");
        map.put("浮尘转霾","common/smog.png");
        map.put("晴转霾","common/smog.png");
        map.put("霾转阴","common/overcast.png");
        map.put("霾转多云","common/cloudy.png");
        map.put("霾转晴","common/fine.png");
        map.put("小到中雪转多云","common/cloudy.png");
        map.put("大雪转多云","common/cloudy.png");
        map.put("雨夹雪转小雨","common/rain.png");
        map.put("大雨转阴","common/rain_2.png");
        map.put("浮尘转多云","common/yangsha.png");
        map.put("多云转霾","common/smog.png");
        map.put("晴转雾","common/smog.png");
        map.put("小雨转中雪","common/snow_2.png");
        map.put("阵雨转小雪","common/snow.png");
        map.put("晴转雷阵雨","common/shower.png");
        map.put("阴转雾","common/smog.png");
        map.put("雷阵雨转中雨","common/shower.png");
        map.put("雷阵雨转大到暴雨","common/shower.png");
        map.put("大到暴雨","common/shower.png");
        map.put("暴雨转中雨","common/shower.png");



        return map;
    }
}
